# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'android:serverUrl' was defined in the Variables tab
# Variable 'ENV_VSTS_MVN_ANDROIDADALUNITY_USERNAME' was defined in the Variables tab
# Variable 'test_repo_branch' was defined in the Variables tab
# Variable 'test_repo_dir' was defined in the Variables tab
# Cron Schedules have been converted using UTC Time Zone and may need to be updated for your location
variables:
- name: BuildParameters.cmdLineArgs
  value: /F:$(Build.SourcesDirectory)+"\adal\src\" /T:9 /O:\"PoliCheck.xml\"
- name: BuildParameters.inputType
  value: Basic
schedules:
- cron: 30 21 * * *
  branches:
    include:
    - dev
  always: true
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: dev
jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted VS2017
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - task: CredScan@2
    name: CredScan_1
    displayName: Run CredScan
    inputs:
      debugMode: false
      folderSuppression: false
  - task: PoliCheck@1
    name: PoliCheck_2
    displayName: Run PoliCheck
    inputs:
      inputType: $(BuildParameters.inputType)
      cmdLineArgs: $(BuildParameters.cmdLineArgs)
      importEx: 0
      optionsFC: 1
      optionsXS: 1
      optionsSEV: 1|2
      optionsPE: 1|2|3|4
  - task: PublishSecurityAnalysisLogs@2
    name: PublishSecurityAnalysisLogs15
    displayName: Publish Security Analysis Logs
  - task: TSAUpload@1
    displayName: TSA upload
    enabled: False
    inputs:
      tsaVersion: TsaV2
      codebase: NewOrUpdate
      codeBaseName: ADALAndroid
      notificationAlias: androididentity@microsoft.com
      codeBaseAdmins: REDMOND\androididentity
      instanceUrlForTsaV2: IDENTITYDIVISION
      projectNameIDENTITYDIVISION: IDDP
      areaPath: IDDP\DevEx-Client-SDK\Android
      iterationPath: IDDP\FY19\Q3
      uploadAPIScan: false
      uploadBinSkim: false
      uploadFortifySCA: false
      uploadFxCop: false
      uploadModernCop: false
      uploadPREfast: false
      uploadRoslyn: false
      uploadTSLint: false
  - task: Gradle@2
    displayName: Snapshot version update
    inputs:
      tasks: versionSnapshot
      publishJUnitResults: false
  - task: Gradle@1
    name: Gradle1
    displayName: Assemble Release
    inputs:
      tasks: 'clean build assembleRelease '
      publishJUnitResults: false
      jdkArchitecture: x86
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - task: Gradle@2
    displayName: Publish to VSTS
    inputs:
      tasks: publish
      publishJUnitResults: false
...
