# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'AdalVersion' was defined in the Variables tab
# Variable 'android:serverUrl' was defined in the Variables tab
# Variable 'test_repo_branch' was defined in the Variables tab
# Variable 'test_repo_dir' was defined in the Variables tab
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: self
    type: git
    ref: master
  - repository: common
    type: github
    name: AzureAD/microsoft-authentication-library-common-for-android
    ref: refs/heads/pedroro/IDDP-pipelines
    endpoint: ANDROID_GITHUB
jobs:
- job: Phase_1
  displayName: SDL and Maven Build
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: true
    persistCredentials: True
  - template: azure-pipelines/templates/steps/credscan-policheck.yml@common
    parameters:
      policheckCmdLineArgsDir: adal
  - template: azure-pipelines/templates/steps/maven-release/generate-release-artifacts.yml@common
    parameters:
      gradleAssembleReleaseTask: adal:clean adal:assembleDist adal:javadocJar
      gradleGeneratePomFiletask: adal:generatePomFileForAdalPublication
      aarSourceFolder: C:\Temp\s\adal\outputs\aar\
      jarSourceFolder: C:\Temp\s\adal\outputs\jar\
      pomSourceFolder: C:\Temp\s\adal\publications\adal\
- job: Phase_2
  displayName: GPG Signing
  cancelTimeoutInMinutes: 1
  dependsOn: Phase_1
  pool:
    name: Hosted Ubuntu 1604
  steps:
  - checkout: self
    clean: true
    submodules: true
  - template: azure-pipelines/templates/steps/maven-release/gpg-signing.yml@common
    parameters:
      gpgSigning: "#!/bin/bash\n\nsudo apt-get update\nsudo apt-get install -y gnupg2\n\nGPG_TTY=$(tty)\nexport GPG_TTY\n\ngpg --import $(public.secureFilePath)\ngpg --import $(private.secureFilePath)\n\n\n\ngpg --batch --no-use-agent --passphrase-file $(passphrase.secureFilePath) --armor --detach-sign $(System.ArtifactsDirectory)/build_outputs/adal-$(AdalVersion).aar\n\ngpg --batch --no-use-agent --passphrase-file $(passphrase.secureFilePath) --armor --detach-sign $(System.ArtifactsDirectory)/build_outputs/adal-$(AdalVersion)-javadoc.jar\n\ngpg --batch --no-use-agent --passphrase-file $(passphrase.secureFilePath) --armor --detach-sign $(System.ArtifactsDirectory)/build_outputs/adal-$(AdalVersion)-sources.jar\n\ngpg --batch --no-use-agent --passphrase-file $(passphrase.secureFilePath) --armor --detach-sign $(System.ArtifactsDirectory)/build_outputs/pom-default.xml\n\ncd $(System.ArtifactsDirectory)/build_outputs/ &&\nfor file in *; do\n if [[ -f \"$file\" ]]; then\n     md5sum -- \"$file\" > \"${file}.md5\"\n fi \n if [[ -f \"$file\" ]]; then\n     shasum -- \"$file\" > \"${file}.sha1\"\n fi\ndone\n\nmkdir  -p $(System.ArtifactsDirectory)/adal/$(AdalVersion)\n\nmv $(System.ArtifactsDirectory)/build_outputs/*.jar $(System.ArtifactsDirectory)/adal/$(AdalVersion)\nmv $(System.ArtifactsDirectory)/build_outputs/*.asc $(System.ArtifactsDirectory)/adal/$(AdalVersion)\nmv $(System.ArtifactsDirectory)/build_outputs/*.aar $(System.ArtifactsDirectory)/adal/$(AdalVersion)\nmv $(System.ArtifactsDirectory)/build_outputs/*.xml $(System.ArtifactsDirectory)/adal/$(AdalVersion)\nmv $(System.ArtifactsDirectory)/build_outputs/*.md5 $(System.ArtifactsDirectory)/adal/$(AdalVersion)\nmv $(System.ArtifactsDirectory)/build_outputs/*.sha1 $(System.ArtifactsDirectory)/adal/$(AdalVersion)\n\n\n\n"
  - template: azure-pipelines/templates/steps/maven-release/upload-to-nexus-sonatype.yml@common
    parameters:
      project: adal
