# ./travis.yml for adal android

language: android

jdk: 
  - oraclejdk7

android:
  components:
    - build-tools-23.0.3
    - android-23
    - extra

env:
    matrix:
      - ANDROID_SDKS=android-23 ANDROID_TARGET=android-23
      
before_install:
  - chmod +x gradlew

script:
  - cd $PWD
  - ./gradlew clean build
